[package]
name = "qsh"
version = "0.1.0"
edition = "2021"

[dependencies]
dynasmrt = "*"
iced-x86 = { optional = true, version = "*" }

[features]
default = ["iced"]
iced = ["iced-x86"]

[profile.release]
debug = true
